name: international_system_of_units
description: The most complete unit converter for Dart/Flutter which also do localizations. Updated to latest version of dart.
version: 1.0.1
repository: https://github.com/clounie/international_system_of_units
homepage: https://github.com/clounie/international_system_of_units/blob/master/packages/international_system_of_units_locale/README.md

environment:
  sdk: '^3.0.0'

dependencies:
  international_system_of_units_locale:
    path: ../international_system_of_units_locale
  intl: ^0.18.1

dev_dependencies:
  intl_translation: ^0.18.2
  lints: ^2.1.0
  test: ^1.24.2
